### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by coagulant** [difio/difio#1]
I'm running `difio-virtualenv-python`

DIFIO_USER_ID=1177
DIFIO_UUID was provided, just ommited for security

Got 500 error in response.

**Comment by atodorov** [comment]
Hi @coagulant,
thanks for your report. 

I believe this error has been fixed already but our cloud provider is having issues at the moment and we can't push new code. I will let you know when the fix has been deployed and verified.

**Comment by atodorov** [comment]
Fix deployed to production. 

If you are having registration issues again, please re-open and post your package list (pip freeze). Thanks.
