### ISSUE TITLE
Can't Refresh Manully Imported Packages

### ISSUE THREAD

**Issue by guzart** [difio/difio#4]
1. From the "Application Details" page
2. Click on the Refresh button next to Last Check-in. 
3. Redirected to a "How To Register Application" page. 
4. When I click on the "import manually" links, nothing happens.

**Comment by atodorov** [comment]
Hi Arturo,
some questions to figure out what is wrong: 

In step 3) - do you see an UUID parameter in the URL, something like http://www.dif.io/register/?uuid=XXX#manual

In step 4) - I suppose you clicked the links to import the package list for your language (Ruby or Python for example). Did you see a page to paste the list of packages, URL should also contain an UUID parameter. Something like this if you used Python:
https://difio-otb.rhcloud.com/application/import/pip-freeze/?uuid=XXXXXXXX

If not, what did you see? 

After step 4) - what does "nothing happens" mean? What exactly happened, which page you saw? Did you get an error?

**Comment by guzart** [comment]
No, I did not click the link of the language.

Sorry, not an issue.
