### ISSUE TITLE
Package status in "Installed Package" column

### ISSUE THREAD

**Issue by techtonik** [difio/difio#9]
A followup to https://github.com/difio/bugs/issues/7#issuecomment-28190425 (1) and https://github.com/difio/bugs/issues/8#issuecomment-28191136

View of package names in "Installed Package" column should reflect their status. For example, there are four possible states of package when it is shown:
1. up-to-date   -- no specific color/style, perhaps a "up to date" tooltip,
   link to previous analytics
2. in-progress  -- data is not yet ready
3. update-available     -- color/style mark, link leads to comparison with
   latest version
4. unknown     -- color/style mark that package is not found in known
   sources

**Comment by atodorov** [comment]
Sorry for the delay.

2) in-progress has been fixed and deployed to production
3) update-available  - nothing to do here really. Links to all analytics vs all available versions are shown as small buttons on the right with the latest version being the first one (sorted by release date actually).
4) unknown - this is CANTFIX at the moment. Currently there's no way to recognize if a package is not available from upstream sources (e.g. private package or a typo in the name) or not yet processed by the backend; or just partially processed. 

Only 1) is left here. I will update this issue with another comment when done.
